{{- if .Values.createVolumes.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv
  namespace: mca-app
spec:
  storageClassName: mongo
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/{{ .Release.Name }}/mongo
{{- end }}